name: Snapshot
on:
  push: 
    branches: [main]

env:
  NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for changesets to work properly
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org
      - run: npm ci

      - name: Publish snapshot
        run: |
          npx changeset version --snapshot next
          npx changeset publish --no-git-tag --snapshot --tag next